<?php

  function shift_cipher_menu() {
    $items['shift_cipher'] = array(
      'title' => 'Shift Cipher',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('shift_cipher_form'),
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
    );
    $items['encoded'] = array(
      'title' => 'Encoded Phrase',
      'page callback' => 'encoded_result',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    );
    return $items;
  }
